name: awesome_pdf_viewer
description: An Awesome PDF Viewer with easy navigation, sharing, and print capabilities.
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  pdfx:
    git:
      url: https://github.com/ScerIO/packages.flutter.git
      path: packages/pdfx
      ref: main
  printing: ^5.10.3
